unbind r
bind r source-file ~/.tmux.conf

set -g base-index 1
set -g pane-base-index 1

set -g default-terminal "tmux-256color"

set -g prefix C-s

set -g mouse on

set-window-option -g mode-keys vi

# Pass Ctrl+J through to applications
bind -n C-j send-keys C-j

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_command}'
set-option -g status-position top

set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "rounded"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'


set -g status-left "#{prefix_highlight}"
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"


set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_status_background "default"
set -g @catppuccin_status_fill "all"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g status-style bg=default


 

